version: '3'

services:
  mysql_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@root_account.123
      MYSQL_USER: testuser
      MYSQL_PASSWORD: mysql_user@123
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/MelodyOpus?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=testuser
      - SPRING_DATASOURCE_PASSWORD=mysql_user@123


volumes:
  db_data: